{% set name = "mgis" %}
{% set version = "3.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://github.com/thelfer/MFrontGenericInterfaceSupport/archive/refs/tags/MFrontGenericInterfaceSupport-{{ version }}.tar.gz
    sha256: dae915201fd20848b69745dabda1a334eb242d823af600825b8b010ddc597640
    patches:
      - patches/site_packages_override_on_windows.patch  # [win]

build:
  number: 1
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('mgis', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.26.4
    - ninja                       # [win]
    - autoconf                    # [not win]
    - make                        # [not win]
  host:
    - python
    - libboost-python-devel
    - mfront
  run:
    - python

test:
  imports:
    - mgis
  requires:
    - pip
  commands:
    - pip check
    # Check for libMFrontGenericInterface.so library
    - test -f $PREFIX/lib/libMFrontGenericInterface.so                      # [not win]
    - test -f $PREFIX/include/MGIS/Config.hxx                               # [not win]
    - test -f $PREFIX/share/mgis/cmake/MFrontGenericInterfaceConfig.cmake   # [not win]


about:
  home: https://thelfer.github.io/mgis/web/index.html
  license: LGPL-3.0-or-later and CECILL-C
  license_file:
    - LGPL-3.0.txt
    - CeCILL-C_V1-en.txt
    - CeCILL-C_V1-fr.txt
  summary: 'MGIS - MFrontGenericInterfaceSupport '
  description: |
    This project aims at proving tools (functions, classes, bindings, etc…) to handle behaviours written using MFront generic interface
  doc_url: https://github.com/thelfer/MFrontGenericInterfaceSupport

extra:
  recipe-maintainers:
    - Krande
    - ldallolio
